### ISSUE TITLE
strand = buf[5] out of range

### ISSUE THREAD

**Issue by chrisclarkson** [ernstlab/ChromTime#3]
Hi I am trying a simple 2 time point analysis with your software (wild-type vs knockout)

My bed files look as follows:
chr1    3000228 3000327
chr1    3000349 3000449
chr1    3000454 3000579
chr1    3000674 3000775
chr1    3001013 3001073

And getting the following error:

```
python ~/ChromTime/ChromTime.py -a W4.bed KO4.bed -c INPUT_WT.bed INPUT_KO.bed -o H3K9ME3_4 -p development -t 4 -g mm9
 {'aligned_fnames': ['formatted_ACTTGA_W4_ME3_merged.bed',
                    'formatted_GGCTAC_K4_ME3_merged.bed'],
 'bin_size': 200,
 'broad': False,
 'control_fnames': ['formatted_INPUT_WT_ME3_merged.bed',
                    'formatted_INPUT_KO_ME3_merged.bed'],
 'data_fname': None,
 'fdr_for_decoding': 0.05,
 'genome': 'mm9',
 'keep_fixed_priors': False,
 'merge_peaks': False,
 'min_dynamic_prior': 0,
 'min_expected_reads': 1,
 'min_gap': 600,
 'mode': 'narrow',
 'model_fname': None,
 'n_threads': 1,
 'n_training_examples': 10000,
 'order_fname': None,
 'out_dir': 'H3K9ME3_4',
 'output_empty_blocks': False,
 'output_signal_files': False,
 'p_value_extend': 0.15,
 'prefix': 'development',
 'q_value_seed': 0.05,
 'shift': 100,
 'skip_training': False,
 'use_broad_window_for_background': False}
[2018-11-10 21:13:49] Estimating initial block boundaries
[2018-11-10 21:13:49] Reading reads from: formatted_ACTTGA_W4_ME3_merged.bed
Traceback (most recent call last):
  File "/home/cc16956/ChromTime/ChromTime.py", line 865, in <module>
    use_broad_window_for_background=args.use_broad_window_for_background)
  File "/home/cc16956/ChromTime/ChromTime.py", line 510, in determine_block_boundaries
    chrom_lengths=chrom_lengths)
  File "/home/cc16956/ChromTime/ChromTime.py", line 55, in read_aligned_reads
    strand = buf[5]
IndexError: list index out of range
```

NOTE when I installed the software with `make` I got the following (could this be making the difference?):

```
make
gcc -c -fPIC -Wall -O3 -std=gnu99 -g C_call_boundary_dynamics.c -o C_call_boundary_dynamics.o
C_call_boundary_dynamics.c: In function âEM_stepâ:
C_call_boundary_dynamics.c:481:26: warning: variable âbck_statusâ set but not used [-Wunused-but-set-variable]
     int fwd_status = -1, bck_status = -1;
                          ^
gcc -shared -Wl,-soname,C_call_boundary_dynamics.so -Wall -O3 -std=gnu99 -g -o C_call_boundary_dynamics.so C_call_boundary_dynamics.o
```

**Comment by pfiziev** [comment]
Hi Chris,

Thank you for bringing up this issue! The problem is that the input file with the aligned reads that you use does not have strand information, which tells whether a read aligned to the '+' or the '-' strand. ChromTime expects that input BED files are formatted as either "chromosome<tab>start<tab>end<tab>strand" or "chromosome<tab>start<tab>end<tab>name<tab>score<tab>strand". The strand information is needed to shift the reads in the correct direction. I updated the code to check for the correct input format and output a more meaningful error message. 

Can you please add the strand information (one of '+' or '-') for all aligned reads and run ChromTime again?
