### ISSUE TITLE
Error in EM step

### ISSUE THREAD

**Issue by ethanashby** [ernstlab/ChromTime#7]
Hello,

I'm encountering an error while running ChromTime in broad mode. Basically, when doing the EM step, the log likelihood decreased between iterations, throwing an error:

Traceback (most recent call last):
  File "/Users/ethanashby/Desktop/chromtime/ChromTime/ChromTime.py", line 924, in <module>
    min_dynamic_prior=args.min_dynamic_prior)
  File "/Users/ethanashby/Desktop/chromtime/ChromTime/call_boundary_dynamics.py", line 2692, in call_boundary_dynamics
    theModel.EM(dict((block_id, blocks[block_id]) for block_id in block_ids_for_training))
  File "/Users/ethanashby/Desktop/chromtime/ChromTime/call_boundary_dynamics.py", line 1228, in EM
    blocks)
call_boundary_dynamics.DecreasingLikelihoodException: Decreasing likelihood. LL delta: -859026.520014

Below are my log file and data.pickle files:

[tbchrom.log](https://github.com/ernstlab/ChromTime/files/6904125/tbchrom.log)
[tbchrom.data.pickle.txt](https://github.com/ernstlab/ChromTime/files/6904140/tbchrom.data.pickle.txt)

The output told me to include the data.pickle file... BUT github does not allow the attachment of pickle files. So I attached it with the .txt extension, even though the file looks crazy.

Please advise!

**Comment by pfiziev** [comment]
Hi Ethan,

Thanks for submitting this issue! What type of data are you using as input (ChIP-seq, DNase etc)? What organism does it come from? Can you please send also the file "Trypanosoma/karyo_file.txt"?

Thanks
Pete

**Comment by ethanashby** [comment]
Hi Pete,

Thanks for the response! I am using CUT&RUN (a procedure similar to ChIP-seq) data as input. The organism is _Trypanosoma brucei_(usingthe 927 genome). The genome file with the list of chromosomes and their associated lengths is attached in here: [karyo_file.txt](https://github.com/ernstlab/ChromTime/files/6918535/karyo_file.txt).

I just realized that I didn't sort my BED files prior to running ChromTime... the program ran successfully on the first replicate but threw this error on the second replicate. Do you think the problem may have to do with sorting BED files and would you recommend I sort them before running ChromTime?

Best,
Ethan

**Comment by pfiziev** [comment]
Hi Ethan,

The order of the reads should not be causing any problems. The input dataset is pretty small (only ~500) peaks, which seems to cause the model optimization routine to fail. I added a temporary fix so that you can run the software without errors and still get reasonable results. Please let me know how this compares to results from the other replicate! We are going to further investigate the issue and can get back to you.

Thanks
Pete
